"""expand_text_column_to_3000

Revision ID: 32c6f03c47fa
Revises: cf671a35c792
Create Date: 2026-01-27 15:57:20.983601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '32c6f03c47fa'
down_revision: Union[str, Sequence[str], None] = 'cf671a35c792'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'post_name',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('posts', 'text',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=3000),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'text',
               existing_type=sa.String(length=3000),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('posts', 'post_name',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=True)
    # ### end Alembic commands ###
